// Code generated by go-swagger; DO NOT EDIT.

package city_bus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/minchao/go-ptx/bus/models"
)

// CityBusAPIEstimatedTimeOfArrivalReader is a Reader for the CityBusAPIEstimatedTimeOfArrival structure.
type CityBusAPIEstimatedTimeOfArrivalReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CityBusAPIEstimatedTimeOfArrivalReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCityBusAPIEstimatedTimeOfArrivalOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCityBusAPIEstimatedTimeOfArrivalOK creates a CityBusAPIEstimatedTimeOfArrivalOK with default headers values
func NewCityBusAPIEstimatedTimeOfArrivalOK() *CityBusAPIEstimatedTimeOfArrivalOK {
	return &CityBusAPIEstimatedTimeOfArrivalOK{}
}

/*CityBusAPIEstimatedTimeOfArrivalOK handles this case with default header values.

OK
*/
type CityBusAPIEstimatedTimeOfArrivalOK struct {
	Payload []*models.ServiceDTOVersion2BusBusN1EstimateTime
}

func (o *CityBusAPIEstimatedTimeOfArrivalOK) Error() string {
	return fmt.Sprintf("[GET /v2/Bus/EstimatedTimeOfArrival/City/{City}][%d] cityBusApiEstimatedTimeOfArrivalOK  %+v", 200, o.Payload)
}

func (o *CityBusAPIEstimatedTimeOfArrivalOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
