# ref https://docs.mergify.io/
pull_request_rules:
  - name: Automatic merge with auto-merge label upon successful build
    conditions:
      - label=auto-merge
      - check-success=Travis CI - Branch
      - check-success=Travis CI - Pull Request
    actions:
      merge:
        method: squash
        strict: smart
        commit_message: title+body
      delete_head_branch: {}