language: go

go:
  - 1.11.x
  - 1.12.x
  - master

matrix:
  allow_failures:
    - go: master

env:
  global:
    - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  - go get -u github.com/go-swagger/go-swagger/cmd/swagger
  - go mod download

script:
  - make validate
  - make lint
  - make test
  - go test -v ./test/integration/...
