language: go

go:
  - 1.11.x
  - 1.12.x
  - master

matrix:
  allow_failures:
    - go: master

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest

script:
  - golangci-lint run -E gofmt ./...
