language: go
dist: xenial

matrix:
  include:
    - go: 1.11.x
    - go: 1.12.x
      env: DEPLOY=true
    - go: master
  allow_failures:
    - go: master

env:
  global:
    - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  # install specific version of go-swagger
  - |
    mkdir -p $GOPATH/src/github.com/go-swagger
    cd $GOPATH/src/github.com/go-swagger
    git clone https://github.com/go-swagger/go-swagger
    cd go-swagger
    git checkout 2f32a5a8
    go install github.com/go-swagger/go-swagger/cmd/swagger
    swagger version
    cd $TRAVIS_BUILD_DIR
  - go mod download

script:
  - if [[ $TRAVIS_BRANCH == "check-spec" ]]; then
    make spec;
    make generate;
    fi
  - make validate
  - make lint
  - make test
  - go test -v ./test/integration/...

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ${TRAVIS_BUILD_DIR}/scripts/check-spec.sh
    on:
      branch: check-spec
      condition: $DEPLOY = true
