language: go
dist: bionic

matrix:
  include:
    - go: 1.12.x
    - go: 1.13.x
    - go: master
  allow_failures:
    - go: master

env:
  global:
    - GO111MODULE=on

cache:
  directories:
    - $GOPATH/pkg/mod

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
  # install go-swagger
  - |
    download_url=$(curl -s https://api.github.com/repos/go-swagger/go-swagger/releases/latest | \
    jq -r '.assets[] | select(.name | contains("'"$(uname | tr '[:upper:]' '[:lower:]')"'_amd64")) | .browser_download_url')
    curl -o /home/travis/bin/swagger -L'#' "$download_url"
    chmod +x /home/travis/bin/swagger
  - go mod download

script:
  - if [[ $TRAVIS_BRANCH == "check-oas-spec" ]]; then
    make spec;
    make generate;
    fi
  - make validate
  - make lint
  - make test
  - make integration

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ${TRAVIS_BUILD_DIR}/scripts/check-oas-spec.sh
    on:
      branch: check-oas-spec
      condition: $TRAVIS_GO_VERSION =~ ^1\.13

notifications:
  email:
    on_success: never
