// Code generated by go-swagger; DO NOT EDIT.

package t_h_s_r

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/go-ptx/rail/v2/models"
)

// THSRAPIAvailableSeatStatus3Reader is a Reader for the THSRAPIAvailableSeatStatus3 structure.
type THSRAPIAvailableSeatStatus3Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *THSRAPIAvailableSeatStatus3Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTHSRAPIAvailableSeatStatus3OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTHSRAPIAvailableSeatStatus3OK creates a THSRAPIAvailableSeatStatus3OK with default headers values
func NewTHSRAPIAvailableSeatStatus3OK() *THSRAPIAvailableSeatStatus3OK {
	return &THSRAPIAvailableSeatStatus3OK{}
}

/*THSRAPIAvailableSeatStatus3OK handles this case with default header values.

Success
*/
type THSRAPIAvailableSeatStatus3OK struct {
	Payload *models.PTXAPIRailModelV2THSRODAvaliableSeatStatusWrapperPTXServiceDTORailSpecificationV2THSRODAvailableSeat
}

func (o *THSRAPIAvailableSeatStatus3OK) Error() string {
	return fmt.Sprintf("[GET /v2/Rail/THSR/AvailableSeatStatus/Train/OD/{OriginStationID}/to/{DestinationStationID}/TrainDate/{TrainDate}][%d] tHSRApiAvailableSeatStatus3OK  %+v", 200, o.Payload)
}

func (o *THSRAPIAvailableSeatStatus3OK) GetPayload() *models.PTXAPIRailModelV2THSRODAvaliableSeatStatusWrapperPTXServiceDTORailSpecificationV2THSRODAvailableSeat {
	return o.Payload
}

func (o *THSRAPIAvailableSeatStatus3OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PTXAPIRailModelV2THSRODAvaliableSeatStatusWrapperPTXServiceDTORailSpecificationV2THSRODAvailableSeat)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
