// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PTXServiceDTOShipSpecificationV3SpecialTimetable SpecialTimetable
//
// swagger:model PTX.Service.DTO.Ship.Specification.V3.SpecialTimetable
type PTXServiceDTOShipSpecificationV3SpecialTimetable struct {

	// ServiceDay
	//
	// 服務日型態
	ServiceDay struct {
		PTXServiceDTOShipSpecificationV3ServiceDay
	} `json:"ServiceDay,omitempty" xml:"ServiceDay,omitempty"`

	// SpecialDays
	//
	// 特殊營運日
	SpecialDays struct {
		PTXServiceDTOShipSpecificationV3SpecialDays
	} `json:"SpecialDays,omitempty" xml:"SpecialDays,omitempty"`

	// Array
	//
	// 航線停靠資料
	// Required: true
	Stoptimes []*PTXServiceDTOShipSpecificationV3Stoptime "json:\"Stoptimes\" xml:\"List`1\""

	// String
	//
	// 班次代碼
	// Required: true
	TripID *string `json:"TripID" xml:"TripID"`
}

// Validate validates this p t x service d t o ship specification v3 special timetable
func (m *PTXServiceDTOShipSpecificationV3SpecialTimetable) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateServiceDay(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSpecialDays(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStoptimes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTripID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PTXServiceDTOShipSpecificationV3SpecialTimetable) validateServiceDay(formats strfmt.Registry) error {
	if swag.IsZero(m.ServiceDay) { // not required
		return nil
	}

	return nil
}

func (m *PTXServiceDTOShipSpecificationV3SpecialTimetable) validateSpecialDays(formats strfmt.Registry) error {
	if swag.IsZero(m.SpecialDays) { // not required
		return nil
	}

	return nil
}

func (m *PTXServiceDTOShipSpecificationV3SpecialTimetable) validateStoptimes(formats strfmt.Registry) error {

	if err := validate.Required("Stoptimes", "body", m.Stoptimes); err != nil {
		return err
	}

	for i := 0; i < len(m.Stoptimes); i++ {
		if swag.IsZero(m.Stoptimes[i]) { // not required
			continue
		}

		if m.Stoptimes[i] != nil {
			if err := m.Stoptimes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Stoptimes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Stoptimes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *PTXServiceDTOShipSpecificationV3SpecialTimetable) validateTripID(formats strfmt.Registry) error {

	if err := validate.Required("TripID", "body", m.TripID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this p t x service d t o ship specification v3 special timetable based on the context it is used
func (m *PTXServiceDTOShipSpecificationV3SpecialTimetable) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateServiceDay(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSpecialDays(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStoptimes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PTXServiceDTOShipSpecificationV3SpecialTimetable) contextValidateServiceDay(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *PTXServiceDTOShipSpecificationV3SpecialTimetable) contextValidateSpecialDays(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *PTXServiceDTOShipSpecificationV3SpecialTimetable) contextValidateStoptimes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Stoptimes); i++ {

		if m.Stoptimes[i] != nil {
			if err := m.Stoptimes[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Stoptimes" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Stoptimes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *PTXServiceDTOShipSpecificationV3SpecialTimetable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PTXServiceDTOShipSpecificationV3SpecialTimetable) UnmarshalBinary(b []byte) error {
	var res PTXServiceDTOShipSpecificationV3SpecialTimetable
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
