// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PTXServiceDTOShipSpecificationV3ODFare ODFare
//
// swagger:model PTX.Service.DTO.Ship.Specification.V3.ODFare
type PTXServiceDTOShipSpecificationV3ODFare struct {

	// PortInformation
	//
	// 迄點港口資訊
	DestinationPort struct {
		PTXServiceDTOShipSpecificationV3PortInformation
	} `json:"DestinationPort,omitempty" xml:"PortInformation,omitempty"`

	// Int32
	//
	// 方向性描述 : [0:'去程',1:'返程',2:'迴圈']
	// Required: true
	Direction *int64 `json:"Direction"`

	// Array
	//
	// 票價內容
	// Required: true
	Fares []*PTXServiceDTOShipSpecificationV3Fare "json:\"Fares\" xml:\"List`1\""

	// PortInformation
	//
	// 起始港口資訊
	OriginPort struct {
		PTXServiceDTOShipSpecificationV3PortInformation
	} `json:"OriginPort,omitempty" xml:"PortInformation,omitempty"`
}

// Validate validates this p t x service d t o ship specification v3 o d fare
func (m *PTXServiceDTOShipSpecificationV3ODFare) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDestinationPort(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDirection(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFares(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOriginPort(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PTXServiceDTOShipSpecificationV3ODFare) validateDestinationPort(formats strfmt.Registry) error {
	if swag.IsZero(m.DestinationPort) { // not required
		return nil
	}

	return nil
}

func (m *PTXServiceDTOShipSpecificationV3ODFare) validateDirection(formats strfmt.Registry) error {

	if err := validate.Required("Direction", "body", m.Direction); err != nil {
		return err
	}

	return nil
}

func (m *PTXServiceDTOShipSpecificationV3ODFare) validateFares(formats strfmt.Registry) error {

	if err := validate.Required("Fares", "body", m.Fares); err != nil {
		return err
	}

	for i := 0; i < len(m.Fares); i++ {
		if swag.IsZero(m.Fares[i]) { // not required
			continue
		}

		if m.Fares[i] != nil {
			if err := m.Fares[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Fares" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Fares" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *PTXServiceDTOShipSpecificationV3ODFare) validateOriginPort(formats strfmt.Registry) error {
	if swag.IsZero(m.OriginPort) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this p t x service d t o ship specification v3 o d fare based on the context it is used
func (m *PTXServiceDTOShipSpecificationV3ODFare) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDestinationPort(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFares(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateOriginPort(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PTXServiceDTOShipSpecificationV3ODFare) contextValidateDestinationPort(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *PTXServiceDTOShipSpecificationV3ODFare) contextValidateFares(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Fares); i++ {

		if m.Fares[i] != nil {
			if err := m.Fares[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Fares" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("Fares" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *PTXServiceDTOShipSpecificationV3ODFare) contextValidateOriginPort(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *PTXServiceDTOShipSpecificationV3ODFare) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PTXServiceDTOShipSpecificationV3ODFare) UnmarshalBinary(b []byte) error {
	var res PTXServiceDTOShipSpecificationV3ODFare
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
