// Code generated by go-swagger; DO NOT EDIT.

package bus_advanced_by_operator

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/go-ptx/bus/v2/models"
)

// CityBusAPIRealTimeNearStopByOperatorReader is a Reader for the CityBusAPIRealTimeNearStopByOperator structure.
type CityBusAPIRealTimeNearStopByOperatorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CityBusAPIRealTimeNearStopByOperatorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCityBusAPIRealTimeNearStopByOperatorOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 299:
		result := NewCityBusAPIRealTimeNearStopByOperatorStatus299()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewCityBusAPIRealTimeNearStopByOperatorNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCityBusAPIRealTimeNearStopByOperatorOK creates a CityBusAPIRealTimeNearStopByOperatorOK with default headers values
func NewCityBusAPIRealTimeNearStopByOperatorOK() *CityBusAPIRealTimeNearStopByOperatorOK {
	return &CityBusAPIRealTimeNearStopByOperatorOK{}
}

/* CityBusAPIRealTimeNearStopByOperatorOK describes a response with status code 200, with default header values.

Success
*/
type CityBusAPIRealTimeNearStopByOperatorOK struct {
	Payload []*models.PTXServiceDTOBusSpecificationV2BusA2Data
}

func (o *CityBusAPIRealTimeNearStopByOperatorOK) Error() string {
	return fmt.Sprintf("[GET /v2/Bus/RealTimeNearStop/City/{City}/OperatorNo/{OperatorNo}][%d] cityBusApiRealTimeNearStopByOperatorOK  %+v", 200, o.Payload)
}
func (o *CityBusAPIRealTimeNearStopByOperatorOK) GetPayload() []*models.PTXServiceDTOBusSpecificationV2BusA2Data {
	return o.Payload
}

func (o *CityBusAPIRealTimeNearStopByOperatorOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCityBusAPIRealTimeNearStopByOperatorStatus299 creates a CityBusAPIRealTimeNearStopByOperatorStatus299 with default headers values
func NewCityBusAPIRealTimeNearStopByOperatorStatus299() *CityBusAPIRealTimeNearStopByOperatorStatus299 {
	return &CityBusAPIRealTimeNearStopByOperatorStatus299{}
}

/* CityBusAPIRealTimeNearStopByOperatorStatus299 describes a response with status code 299, with default header values.

加入參數'?health=true'即可查詢此API服務的健康狀態
*/
type CityBusAPIRealTimeNearStopByOperatorStatus299 struct {
	Payload *models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth
}

func (o *CityBusAPIRealTimeNearStopByOperatorStatus299) Error() string {
	return fmt.Sprintf("[GET /v2/Bus/RealTimeNearStop/City/{City}/OperatorNo/{OperatorNo}][%d] cityBusApiRealTimeNearStopByOperatorStatus299  %+v", 299, o.Payload)
}
func (o *CityBusAPIRealTimeNearStopByOperatorStatus299) GetPayload() *models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth {
	return o.Payload
}

func (o *CityBusAPIRealTimeNearStopByOperatorStatus299) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCityBusAPIRealTimeNearStopByOperatorNotModified creates a CityBusAPIRealTimeNearStopByOperatorNotModified with default headers values
func NewCityBusAPIRealTimeNearStopByOperatorNotModified() *CityBusAPIRealTimeNearStopByOperatorNotModified {
	return &CityBusAPIRealTimeNearStopByOperatorNotModified{}
}

/* CityBusAPIRealTimeNearStopByOperatorNotModified describes a response with status code 304, with default header values.

服務端會在Response加上Last-Modified header，表示最近的更新時間。客戶端能利用此時間，於Request加上If-Modified-Since header，若沒有更新，服務端會回應304 StatusCode且空值Content
*/
type CityBusAPIRealTimeNearStopByOperatorNotModified struct {
}

func (o *CityBusAPIRealTimeNearStopByOperatorNotModified) Error() string {
	return fmt.Sprintf("[GET /v2/Bus/RealTimeNearStop/City/{City}/OperatorNo/{OperatorNo}][%d] cityBusApiRealTimeNearStopByOperatorNotModified ", 304)
}

func (o *CityBusAPIRealTimeNearStopByOperatorNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
