// Code generated by go-swagger; DO NOT EDIT.

package t_r_a

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/go-ptx/rail/v2/models"
)

// TRAAPILiveTrainDelay2154Reader is a Reader for the TRAAPILiveTrainDelay2154 structure.
type TRAAPILiveTrainDelay2154Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TRAAPILiveTrainDelay2154Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTRAAPILiveTrainDelay2154OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 299:
		result := NewTRAAPILiveTrainDelay2154Status299()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewTRAAPILiveTrainDelay2154NotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTRAAPILiveTrainDelay2154OK creates a TRAAPILiveTrainDelay2154OK with default headers values
func NewTRAAPILiveTrainDelay2154OK() *TRAAPILiveTrainDelay2154OK {
	return &TRAAPILiveTrainDelay2154OK{}
}

/* TRAAPILiveTrainDelay2154OK describes a response with status code 200, with default header values.

Success
*/
type TRAAPILiveTrainDelay2154OK struct {
	Payload []*models.PTXServiceDTORailSpecificationV2TRARailLiveTrainDelay
}

func (o *TRAAPILiveTrainDelay2154OK) Error() string {
	return fmt.Sprintf("[GET /v2/Rail/TRA/LiveTrainDelay][%d] tRAApiLiveTrainDelay2154OK  %+v", 200, o.Payload)
}
func (o *TRAAPILiveTrainDelay2154OK) GetPayload() []*models.PTXServiceDTORailSpecificationV2TRARailLiveTrainDelay {
	return o.Payload
}

func (o *TRAAPILiveTrainDelay2154OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTRAAPILiveTrainDelay2154Status299 creates a TRAAPILiveTrainDelay2154Status299 with default headers values
func NewTRAAPILiveTrainDelay2154Status299() *TRAAPILiveTrainDelay2154Status299 {
	return &TRAAPILiveTrainDelay2154Status299{}
}

/* TRAAPILiveTrainDelay2154Status299 describes a response with status code 299, with default header values.

加入參數'?health=true'即可查詢此API服務的健康狀態
*/
type TRAAPILiveTrainDelay2154Status299 struct {
	Payload *models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth
}

func (o *TRAAPILiveTrainDelay2154Status299) Error() string {
	return fmt.Sprintf("[GET /v2/Rail/TRA/LiveTrainDelay][%d] tRAApiLiveTrainDelay2154Status299  %+v", 299, o.Payload)
}
func (o *TRAAPILiveTrainDelay2154Status299) GetPayload() *models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth {
	return o.Payload
}

func (o *TRAAPILiveTrainDelay2154Status299) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTRAAPILiveTrainDelay2154NotModified creates a TRAAPILiveTrainDelay2154NotModified with default headers values
func NewTRAAPILiveTrainDelay2154NotModified() *TRAAPILiveTrainDelay2154NotModified {
	return &TRAAPILiveTrainDelay2154NotModified{}
}

/* TRAAPILiveTrainDelay2154NotModified describes a response with status code 304, with default header values.

服務端會在Response加上Last-Modified header，表示最近的更新時間。客戶端能利用此時間，於Request加上If-Modified-Since header，若沒有更新，服務端會回應304 StatusCode且空值Content
*/
type TRAAPILiveTrainDelay2154NotModified struct {
}

func (o *TRAAPILiveTrainDelay2154NotModified) Error() string {
	return fmt.Sprintf("[GET /v2/Rail/TRA/LiveTrainDelay][%d] tRAApiLiveTrainDelay2154NotModified ", 304)
}

func (o *TRAAPILiveTrainDelay2154NotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
