// Code generated by go-swagger; DO NOT EDIT.

package air

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAirAPIAirport20101Params creates a new AirAPIAirport20101Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAirAPIAirport20101Params() *AirAPIAirport20101Params {
	return &AirAPIAirport20101Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewAirAPIAirport20101ParamsWithTimeout creates a new AirAPIAirport20101Params object
// with the ability to set a timeout on a request.
func NewAirAPIAirport20101ParamsWithTimeout(timeout time.Duration) *AirAPIAirport20101Params {
	return &AirAPIAirport20101Params{
		timeout: timeout,
	}
}

// NewAirAPIAirport20101ParamsWithContext creates a new AirAPIAirport20101Params object
// with the ability to set a context for a request.
func NewAirAPIAirport20101ParamsWithContext(ctx context.Context) *AirAPIAirport20101Params {
	return &AirAPIAirport20101Params{
		Context: ctx,
	}
}

// NewAirAPIAirport20101ParamsWithHTTPClient creates a new AirAPIAirport20101Params object
// with the ability to set a custom HTTPClient for a request.
func NewAirAPIAirport20101ParamsWithHTTPClient(client *http.Client) *AirAPIAirport20101Params {
	return &AirAPIAirport20101Params{
		HTTPClient: client,
	}
}

/* AirAPIAirport20101Params contains all the parameters to send to the API endpoint
   for the air Api airport 2010 1 operation.

   Typically these are written to a http.Request.
*/
type AirAPIAirport20101Params struct {

	/* DollarFormat.

	   指定來源格式
	*/
	DollarFormat string

	/* IATA.

	   機場代碼
	*/
	IATA string

	/* Health.

	   加入參數'?health=true'即可查詢此API服務的健康狀態
	*/
	Health *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the air Api airport 2010 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AirAPIAirport20101Params) WithDefaults() *AirAPIAirport20101Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the air Api airport 2010 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AirAPIAirport20101Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the air Api airport 2010 1 params
func (o *AirAPIAirport20101Params) WithTimeout(timeout time.Duration) *AirAPIAirport20101Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the air Api airport 2010 1 params
func (o *AirAPIAirport20101Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the air Api airport 2010 1 params
func (o *AirAPIAirport20101Params) WithContext(ctx context.Context) *AirAPIAirport20101Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the air Api airport 2010 1 params
func (o *AirAPIAirport20101Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the air Api airport 2010 1 params
func (o *AirAPIAirport20101Params) WithHTTPClient(client *http.Client) *AirAPIAirport20101Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the air Api airport 2010 1 params
func (o *AirAPIAirport20101Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarFormat adds the dollarFormat to the air Api airport 2010 1 params
func (o *AirAPIAirport20101Params) WithDollarFormat(dollarFormat string) *AirAPIAirport20101Params {
	o.SetDollarFormat(dollarFormat)
	return o
}

// SetDollarFormat adds the dollarFormat to the air Api airport 2010 1 params
func (o *AirAPIAirport20101Params) SetDollarFormat(dollarFormat string) {
	o.DollarFormat = dollarFormat
}

// WithIATA adds the iATA to the air Api airport 2010 1 params
func (o *AirAPIAirport20101Params) WithIATA(iATA string) *AirAPIAirport20101Params {
	o.SetIATA(iATA)
	return o
}

// SetIATA adds the iATA to the air Api airport 2010 1 params
func (o *AirAPIAirport20101Params) SetIATA(iATA string) {
	o.IATA = iATA
}

// WithHealth adds the health to the air Api airport 2010 1 params
func (o *AirAPIAirport20101Params) WithHealth(health *string) *AirAPIAirport20101Params {
	o.SetHealth(health)
	return o
}

// SetHealth adds the health to the air Api airport 2010 1 params
func (o *AirAPIAirport20101Params) SetHealth(health *string) {
	o.Health = health
}

// WriteToRequest writes these params to a swagger request
func (o *AirAPIAirport20101Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param $format
	qrDollarFormat := o.DollarFormat
	qDollarFormat := qrDollarFormat
	if qDollarFormat != "" {

		if err := r.SetQueryParam("$format", qDollarFormat); err != nil {
			return err
		}
	}

	// path param IATA
	if err := r.SetPathParam("IATA", o.IATA); err != nil {
		return err
	}

	if o.Health != nil {

		// query param health
		var qrHealth string

		if o.Health != nil {
			qrHealth = *o.Health
		}
		qHealth := qrHealth
		if qHealth != "" {

			if err := r.SetQueryParam("health", qHealth); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
