// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PTXServiceDTORailSpecificationV3TRANetworkLine Line
//
// 路線基本資料
//
// swagger:model PTX.Service.DTO.Rail.Specification.V3.TRA.Network.Line
type PTXServiceDTORailSpecificationV3TRANetworkLine struct {

	// String
	//
	// 路線代碼
	// Required: true
	LineID *string `json:"LineID"`

	// String
	//
	// 路線編號
	// Required: true
	LineNo *string `json:"LineNo"`
}

// Validate validates this p t x service d t o rail specification v3 t r a network line
func (m *PTXServiceDTORailSpecificationV3TRANetworkLine) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLineID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLineNo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PTXServiceDTORailSpecificationV3TRANetworkLine) validateLineID(formats strfmt.Registry) error {

	if err := validate.Required("LineID", "body", m.LineID); err != nil {
		return err
	}

	return nil
}

func (m *PTXServiceDTORailSpecificationV3TRANetworkLine) validateLineNo(formats strfmt.Registry) error {

	if err := validate.Required("LineNo", "body", m.LineNo); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PTXServiceDTORailSpecificationV3TRANetworkLine) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PTXServiceDTORailSpecificationV3TRANetworkLine) UnmarshalBinary(b []byte) error {
	var res PTXServiceDTORailSpecificationV3TRANetworkLine
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
