// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PTXServiceDTORailSpecificationV3TRAStationExitExitMapURL ExitMapURL
//
// swagger:model PTX.Service.DTO.Rail.Specification.V3.TRA.StationExit.ExitMapURL
type PTXServiceDTORailSpecificationV3TRAStationExitExitMapURL struct {

	// String
	//
	// 樓層
	FloorLevel string `json:"FloorLevel,omitempty" xml:"FloorLevel,omitempty"`

	// NameType
	//
	// 車站出入口簡圖名稱
	// Required: true
	MapName struct {
		PTXServiceDTOSharedSpecificationV3BaseNameType
	} `json:"MapName" xml:"NameType"`

	// String
	//
	// 車站出入口簡圖網址
	MapURL string `json:"MapURL,omitempty" xml:"MapURL,omitempty"`
}

// Validate validates this p t x service d t o rail specification v3 t r a station exit exit map URL
func (m *PTXServiceDTORailSpecificationV3TRAStationExitExitMapURL) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMapName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PTXServiceDTORailSpecificationV3TRAStationExitExitMapURL) validateMapName(formats strfmt.Registry) error {

	return nil
}

// ContextValidate validate this p t x service d t o rail specification v3 t r a station exit exit map URL based on the context it is used
func (m *PTXServiceDTORailSpecificationV3TRAStationExitExitMapURL) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMapName(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PTXServiceDTORailSpecificationV3TRAStationExitExitMapURL) contextValidateMapName(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *PTXServiceDTORailSpecificationV3TRAStationExitExitMapURL) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PTXServiceDTORailSpecificationV3TRAStationExitExitMapURL) UnmarshalBinary(b []byte) error {
	var res PTXServiceDTORailSpecificationV3TRAStationExitExitMapURL
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
