// Code generated by go-swagger; DO NOT EDIT.

package taiwan_trip_bus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/minchao/go-ptx/tourism/models"
)

// TaiwanTripBusAPIEstimatedTimeOfArrivalReader is a Reader for the TaiwanTripBusAPIEstimatedTimeOfArrival structure.
type TaiwanTripBusAPIEstimatedTimeOfArrivalReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TaiwanTripBusAPIEstimatedTimeOfArrivalReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTaiwanTripBusAPIEstimatedTimeOfArrivalOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTaiwanTripBusAPIEstimatedTimeOfArrivalOK creates a TaiwanTripBusAPIEstimatedTimeOfArrivalOK with default headers values
func NewTaiwanTripBusAPIEstimatedTimeOfArrivalOK() *TaiwanTripBusAPIEstimatedTimeOfArrivalOK {
	return &TaiwanTripBusAPIEstimatedTimeOfArrivalOK{}
}

/*TaiwanTripBusAPIEstimatedTimeOfArrivalOK handles this case with default header values.

OK
*/
type TaiwanTripBusAPIEstimatedTimeOfArrivalOK struct {
	Payload []*models.ServiceDTOVersion2TaiwanTripBusBusN1EstimateTime
}

func (o *TaiwanTripBusAPIEstimatedTimeOfArrivalOK) Error() string {
	return fmt.Sprintf("[GET /v2/Tourism/Bus/EstimatedTimeOfArrival/TaiwanTrip][%d] taiwanTripBusApiEstimatedTimeOfArrivalOK  %+v", 200, o.Payload)
}

func (o *TaiwanTripBusAPIEstimatedTimeOfArrivalOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
