// Code generated by go-swagger; DO NOT EDIT.

package ship_by_route_type

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewShipRouteTypeSpecificSchedule23262Params creates a new ShipRouteTypeSpecificSchedule23262Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewShipRouteTypeSpecificSchedule23262Params() *ShipRouteTypeSpecificSchedule23262Params {
	return &ShipRouteTypeSpecificSchedule23262Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewShipRouteTypeSpecificSchedule23262ParamsWithTimeout creates a new ShipRouteTypeSpecificSchedule23262Params object
// with the ability to set a timeout on a request.
func NewShipRouteTypeSpecificSchedule23262ParamsWithTimeout(timeout time.Duration) *ShipRouteTypeSpecificSchedule23262Params {
	return &ShipRouteTypeSpecificSchedule23262Params{
		timeout: timeout,
	}
}

// NewShipRouteTypeSpecificSchedule23262ParamsWithContext creates a new ShipRouteTypeSpecificSchedule23262Params object
// with the ability to set a context for a request.
func NewShipRouteTypeSpecificSchedule23262ParamsWithContext(ctx context.Context) *ShipRouteTypeSpecificSchedule23262Params {
	return &ShipRouteTypeSpecificSchedule23262Params{
		Context: ctx,
	}
}

// NewShipRouteTypeSpecificSchedule23262ParamsWithHTTPClient creates a new ShipRouteTypeSpecificSchedule23262Params object
// with the ability to set a custom HTTPClient for a request.
func NewShipRouteTypeSpecificSchedule23262ParamsWithHTTPClient(client *http.Client) *ShipRouteTypeSpecificSchedule23262Params {
	return &ShipRouteTypeSpecificSchedule23262Params{
		HTTPClient: client,
	}
}

/* ShipRouteTypeSpecificSchedule23262Params contains all the parameters to send to the API endpoint
   for the ship route type specific schedule2 3262 operation.

   Typically these are written to a http.Request.
*/
type ShipRouteTypeSpecificSchedule23262Params struct {

	/* DollarFilter.

	   過濾
	*/
	DollarFilter *string

	/* DollarFormat.

	   指定來源格式
	*/
	DollarFormat string

	/* DollarOrderby.

	   排序
	*/
	DollarOrderby *string

	/* DollarSelect.

	   挑選
	*/
	DollarSelect *string

	/* DollarSkip.

	   跳過前幾筆
	*/
	DollarSkip *string

	/* DollarTop.

	   取前幾筆

	   Default: 30
	*/
	DollarTop *int64

	/* RouteID.

	   指定航運路線代碼
	*/
	RouteID string

	/* Health.

	   加入參數'?health=true'即可查詢此API服務的健康狀態
	*/
	Health *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the ship route type specific schedule2 3262 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShipRouteTypeSpecificSchedule23262Params) WithDefaults() *ShipRouteTypeSpecificSchedule23262Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the ship route type specific schedule2 3262 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ShipRouteTypeSpecificSchedule23262Params) SetDefaults() {
	var (
		dollarTopDefault = int64(30)
	)

	val := ShipRouteTypeSpecificSchedule23262Params{
		DollarTop: &dollarTopDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) WithTimeout(timeout time.Duration) *ShipRouteTypeSpecificSchedule23262Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) WithContext(ctx context.Context) *ShipRouteTypeSpecificSchedule23262Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) WithHTTPClient(client *http.Client) *ShipRouteTypeSpecificSchedule23262Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarFilter adds the dollarFilter to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) WithDollarFilter(dollarFilter *string) *ShipRouteTypeSpecificSchedule23262Params {
	o.SetDollarFilter(dollarFilter)
	return o
}

// SetDollarFilter adds the dollarFilter to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) SetDollarFilter(dollarFilter *string) {
	o.DollarFilter = dollarFilter
}

// WithDollarFormat adds the dollarFormat to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) WithDollarFormat(dollarFormat string) *ShipRouteTypeSpecificSchedule23262Params {
	o.SetDollarFormat(dollarFormat)
	return o
}

// SetDollarFormat adds the dollarFormat to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) SetDollarFormat(dollarFormat string) {
	o.DollarFormat = dollarFormat
}

// WithDollarOrderby adds the dollarOrderby to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) WithDollarOrderby(dollarOrderby *string) *ShipRouteTypeSpecificSchedule23262Params {
	o.SetDollarOrderby(dollarOrderby)
	return o
}

// SetDollarOrderby adds the dollarOrderby to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) SetDollarOrderby(dollarOrderby *string) {
	o.DollarOrderby = dollarOrderby
}

// WithDollarSelect adds the dollarSelect to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) WithDollarSelect(dollarSelect *string) *ShipRouteTypeSpecificSchedule23262Params {
	o.SetDollarSelect(dollarSelect)
	return o
}

// SetDollarSelect adds the dollarSelect to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) SetDollarSelect(dollarSelect *string) {
	o.DollarSelect = dollarSelect
}

// WithDollarSkip adds the dollarSkip to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) WithDollarSkip(dollarSkip *string) *ShipRouteTypeSpecificSchedule23262Params {
	o.SetDollarSkip(dollarSkip)
	return o
}

// SetDollarSkip adds the dollarSkip to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) SetDollarSkip(dollarSkip *string) {
	o.DollarSkip = dollarSkip
}

// WithDollarTop adds the dollarTop to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) WithDollarTop(dollarTop *int64) *ShipRouteTypeSpecificSchedule23262Params {
	o.SetDollarTop(dollarTop)
	return o
}

// SetDollarTop adds the dollarTop to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) SetDollarTop(dollarTop *int64) {
	o.DollarTop = dollarTop
}

// WithRouteID adds the routeID to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) WithRouteID(routeID string) *ShipRouteTypeSpecificSchedule23262Params {
	o.SetRouteID(routeID)
	return o
}

// SetRouteID adds the routeId to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) SetRouteID(routeID string) {
	o.RouteID = routeID
}

// WithHealth adds the health to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) WithHealth(health *string) *ShipRouteTypeSpecificSchedule23262Params {
	o.SetHealth(health)
	return o
}

// SetHealth adds the health to the ship route type specific schedule2 3262 params
func (o *ShipRouteTypeSpecificSchedule23262Params) SetHealth(health *string) {
	o.Health = health
}

// WriteToRequest writes these params to a swagger request
func (o *ShipRouteTypeSpecificSchedule23262Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DollarFilter != nil {

		// query param $filter
		var qrDollarFilter string

		if o.DollarFilter != nil {
			qrDollarFilter = *o.DollarFilter
		}
		qDollarFilter := qrDollarFilter
		if qDollarFilter != "" {

			if err := r.SetQueryParam("$filter", qDollarFilter); err != nil {
				return err
			}
		}
	}

	// query param $format
	qrDollarFormat := o.DollarFormat
	qDollarFormat := qrDollarFormat
	if qDollarFormat != "" {

		if err := r.SetQueryParam("$format", qDollarFormat); err != nil {
			return err
		}
	}

	if o.DollarOrderby != nil {

		// query param $orderby
		var qrDollarOrderby string

		if o.DollarOrderby != nil {
			qrDollarOrderby = *o.DollarOrderby
		}
		qDollarOrderby := qrDollarOrderby
		if qDollarOrderby != "" {

			if err := r.SetQueryParam("$orderby", qDollarOrderby); err != nil {
				return err
			}
		}
	}

	if o.DollarSelect != nil {

		// query param $select
		var qrDollarSelect string

		if o.DollarSelect != nil {
			qrDollarSelect = *o.DollarSelect
		}
		qDollarSelect := qrDollarSelect
		if qDollarSelect != "" {

			if err := r.SetQueryParam("$select", qDollarSelect); err != nil {
				return err
			}
		}
	}

	if o.DollarSkip != nil {

		// query param $skip
		var qrDollarSkip string

		if o.DollarSkip != nil {
			qrDollarSkip = *o.DollarSkip
		}
		qDollarSkip := qrDollarSkip
		if qDollarSkip != "" {

			if err := r.SetQueryParam("$skip", qDollarSkip); err != nil {
				return err
			}
		}
	}

	if o.DollarTop != nil {

		// query param $top
		var qrDollarTop int64

		if o.DollarTop != nil {
			qrDollarTop = *o.DollarTop
		}
		qDollarTop := swag.FormatInt64(qrDollarTop)
		if qDollarTop != "" {

			if err := r.SetQueryParam("$top", qDollarTop); err != nil {
				return err
			}
		}
	}

	// path param RouteID
	if err := r.SetPathParam("RouteID", o.RouteID); err != nil {
		return err
	}

	if o.Health != nil {

		// query param health
		var qrHealth string

		if o.Health != nil {
			qrHealth = *o.Health
		}
		qHealth := qrHealth
		if qHealth != "" {

			if err := r.SetQueryParam("health", qHealth); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
