// Code generated by go-swagger; DO NOT EDIT.

package city_bus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/go-ptx/bus/v2/models"
)

// CityBusAPIDataVersionReader is a Reader for the CityBusAPIDataVersion structure.
type CityBusAPIDataVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CityBusAPIDataVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCityBusAPIDataVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 299:
		result := NewCityBusAPIDataVersionStatus299()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCityBusAPIDataVersionOK creates a CityBusAPIDataVersionOK with default headers values
func NewCityBusAPIDataVersionOK() *CityBusAPIDataVersionOK {
	return &CityBusAPIDataVersionOK{}
}

/*CityBusAPIDataVersionOK handles this case with default header values.

OK
*/
type CityBusAPIDataVersionOK struct {
	Payload *models.ServiceDTOVersion2BusBusVersion
}

func (o *CityBusAPIDataVersionOK) Error() string {
	return fmt.Sprintf("[GET /v2/Bus/DataVersion/City/{City}][%d] cityBusApiDataVersionOK  %+v", 200, o.Payload)
}

func (o *CityBusAPIDataVersionOK) GetPayload() *models.ServiceDTOVersion2BusBusVersion {
	return o.Payload
}

func (o *CityBusAPIDataVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceDTOVersion2BusBusVersion)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCityBusAPIDataVersionStatus299 creates a CityBusAPIDataVersionStatus299 with default headers values
func NewCityBusAPIDataVersionStatus299() *CityBusAPIDataVersionStatus299 {
	return &CityBusAPIDataVersionStatus299{}
}

/*CityBusAPIDataVersionStatus299 handles this case with default header values.

加入參數'?health=true'即可查詢此API服務的健康狀態
*/
type CityBusAPIDataVersionStatus299 struct {
	Payload *models.ServiceDTOVersion3BaseDisplayHealth
}

func (o *CityBusAPIDataVersionStatus299) Error() string {
	return fmt.Sprintf("[GET /v2/Bus/DataVersion/City/{City}][%d] cityBusApiDataVersionStatus299  %+v", 299, o.Payload)
}

func (o *CityBusAPIDataVersionStatus299) GetPayload() *models.ServiceDTOVersion3BaseDisplayHealth {
	return o.Payload
}

func (o *CityBusAPIDataVersionStatus299) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ServiceDTOVersion3BaseDisplayHealth)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
