// Code generated by go-swagger; DO NOT EDIT.

package city_bus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCityBusAPIDataVersionParams creates a new CityBusAPIDataVersionParams object
// with the default values initialized.
func NewCityBusAPIDataVersionParams() *CityBusAPIDataVersionParams {
	var ()
	return &CityBusAPIDataVersionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCityBusAPIDataVersionParamsWithTimeout creates a new CityBusAPIDataVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCityBusAPIDataVersionParamsWithTimeout(timeout time.Duration) *CityBusAPIDataVersionParams {
	var ()
	return &CityBusAPIDataVersionParams{

		timeout: timeout,
	}
}

// NewCityBusAPIDataVersionParamsWithContext creates a new CityBusAPIDataVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewCityBusAPIDataVersionParamsWithContext(ctx context.Context) *CityBusAPIDataVersionParams {
	var ()
	return &CityBusAPIDataVersionParams{

		Context: ctx,
	}
}

// NewCityBusAPIDataVersionParamsWithHTTPClient creates a new CityBusAPIDataVersionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCityBusAPIDataVersionParamsWithHTTPClient(client *http.Client) *CityBusAPIDataVersionParams {
	var ()
	return &CityBusAPIDataVersionParams{
		HTTPClient: client,
	}
}

/*CityBusAPIDataVersionParams contains all the parameters to send to the API endpoint
for the city bus Api data version operation typically these are written to a http.Request
*/
type CityBusAPIDataVersionParams struct {

	/*DollarFormat
	  指定來源格式

	*/
	DollarFormat string
	/*City
	  欲查詢縣市

	*/
	City string
	/*Health
	  加入參數'?health=true'即可查詢此API服務的健康狀態

	*/
	Health *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the city bus Api data version params
func (o *CityBusAPIDataVersionParams) WithTimeout(timeout time.Duration) *CityBusAPIDataVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the city bus Api data version params
func (o *CityBusAPIDataVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the city bus Api data version params
func (o *CityBusAPIDataVersionParams) WithContext(ctx context.Context) *CityBusAPIDataVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the city bus Api data version params
func (o *CityBusAPIDataVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the city bus Api data version params
func (o *CityBusAPIDataVersionParams) WithHTTPClient(client *http.Client) *CityBusAPIDataVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the city bus Api data version params
func (o *CityBusAPIDataVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarFormat adds the dollarFormat to the city bus Api data version params
func (o *CityBusAPIDataVersionParams) WithDollarFormat(dollarFormat string) *CityBusAPIDataVersionParams {
	o.SetDollarFormat(dollarFormat)
	return o
}

// SetDollarFormat adds the dollarFormat to the city bus Api data version params
func (o *CityBusAPIDataVersionParams) SetDollarFormat(dollarFormat string) {
	o.DollarFormat = dollarFormat
}

// WithCity adds the city to the city bus Api data version params
func (o *CityBusAPIDataVersionParams) WithCity(city string) *CityBusAPIDataVersionParams {
	o.SetCity(city)
	return o
}

// SetCity adds the city to the city bus Api data version params
func (o *CityBusAPIDataVersionParams) SetCity(city string) {
	o.City = city
}

// WithHealth adds the health to the city bus Api data version params
func (o *CityBusAPIDataVersionParams) WithHealth(health *string) *CityBusAPIDataVersionParams {
	o.SetHealth(health)
	return o
}

// SetHealth adds the health to the city bus Api data version params
func (o *CityBusAPIDataVersionParams) SetHealth(health *string) {
	o.Health = health
}

// WriteToRequest writes these params to a swagger request
func (o *CityBusAPIDataVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param $format
	qrDollarFormat := o.DollarFormat
	qDollarFormat := qrDollarFormat
	if qDollarFormat != "" {
		if err := r.SetQueryParam("$format", qDollarFormat); err != nil {
			return err
		}
	}

	// path param City
	if err := r.SetPathParam("City", o.City); err != nil {
		return err
	}

	if o.Health != nil {

		// query param health
		var qrHealth string
		if o.Health != nil {
			qrHealth = *o.Health
		}
		qHealth := qrHealth
		if qHealth != "" {
			if err := r.SetQueryParam("health", qHealth); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
