// Code generated by go-swagger; DO NOT EDIT.

package city_bus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/go-ptx/bus/v2/models"
)

// CityBusAPIStop2036Reader is a Reader for the CityBusAPIStop2036 structure.
type CityBusAPIStop2036Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CityBusAPIStop2036Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCityBusAPIStop2036OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 299:
		result := NewCityBusAPIStop2036Status299()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewCityBusAPIStop2036NotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCityBusAPIStop2036OK creates a CityBusAPIStop2036OK with default headers values
func NewCityBusAPIStop2036OK() *CityBusAPIStop2036OK {
	return &CityBusAPIStop2036OK{}
}

/* CityBusAPIStop2036OK describes a response with status code 200, with default header values.

Success
*/
type CityBusAPIStop2036OK struct {
	Payload []*models.PTXServiceDTOBusSpecificationV2BusStop
}

func (o *CityBusAPIStop2036OK) Error() string {
	return fmt.Sprintf("[GET /v2/Bus/Stop/City/{City}][%d] cityBusApiStop2036OK  %+v", 200, o.Payload)
}
func (o *CityBusAPIStop2036OK) GetPayload() []*models.PTXServiceDTOBusSpecificationV2BusStop {
	return o.Payload
}

func (o *CityBusAPIStop2036OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCityBusAPIStop2036Status299 creates a CityBusAPIStop2036Status299 with default headers values
func NewCityBusAPIStop2036Status299() *CityBusAPIStop2036Status299 {
	return &CityBusAPIStop2036Status299{}
}

/* CityBusAPIStop2036Status299 describes a response with status code 299, with default header values.

加入參數'?health=true'即可查詢此API服務的健康狀態
*/
type CityBusAPIStop2036Status299 struct {
	Payload *models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth
}

func (o *CityBusAPIStop2036Status299) Error() string {
	return fmt.Sprintf("[GET /v2/Bus/Stop/City/{City}][%d] cityBusApiStop2036Status299  %+v", 299, o.Payload)
}
func (o *CityBusAPIStop2036Status299) GetPayload() *models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth {
	return o.Payload
}

func (o *CityBusAPIStop2036Status299) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCityBusAPIStop2036NotModified creates a CityBusAPIStop2036NotModified with default headers values
func NewCityBusAPIStop2036NotModified() *CityBusAPIStop2036NotModified {
	return &CityBusAPIStop2036NotModified{}
}

/* CityBusAPIStop2036NotModified describes a response with status code 304, with default header values.

服務端會在Response加上Last-Modified header，表示最近的更新時間。客戶端能利用此時間，於Request加上If-Modified-Since header，若沒有更新，服務端會回應304 StatusCode且空值Content
*/
type CityBusAPIStop2036NotModified struct {
}

func (o *CityBusAPIStop2036NotModified) Error() string {
	return fmt.Sprintf("[GET /v2/Bus/Stop/City/{City}][%d] cityBusApiStop2036NotModified ", 304)
}

func (o *CityBusAPIStop2036NotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
