// Code generated by go-swagger; DO NOT EDIT.

package city_bus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCityBusAPIRoute20351Params creates a new CityBusAPIRoute20351Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCityBusAPIRoute20351Params() *CityBusAPIRoute20351Params {
	return &CityBusAPIRoute20351Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewCityBusAPIRoute20351ParamsWithTimeout creates a new CityBusAPIRoute20351Params object
// with the ability to set a timeout on a request.
func NewCityBusAPIRoute20351ParamsWithTimeout(timeout time.Duration) *CityBusAPIRoute20351Params {
	return &CityBusAPIRoute20351Params{
		timeout: timeout,
	}
}

// NewCityBusAPIRoute20351ParamsWithContext creates a new CityBusAPIRoute20351Params object
// with the ability to set a context for a request.
func NewCityBusAPIRoute20351ParamsWithContext(ctx context.Context) *CityBusAPIRoute20351Params {
	return &CityBusAPIRoute20351Params{
		Context: ctx,
	}
}

// NewCityBusAPIRoute20351ParamsWithHTTPClient creates a new CityBusAPIRoute20351Params object
// with the ability to set a custom HTTPClient for a request.
func NewCityBusAPIRoute20351ParamsWithHTTPClient(client *http.Client) *CityBusAPIRoute20351Params {
	return &CityBusAPIRoute20351Params{
		HTTPClient: client,
	}
}

/* CityBusAPIRoute20351Params contains all the parameters to send to the API endpoint
   for the city bus Api route 2035 1 operation.

   Typically these are written to a http.Request.
*/
type CityBusAPIRoute20351Params struct {

	/* DollarFilter.

	   過濾
	*/
	DollarFilter *string

	/* DollarFormat.

	   指定來源格式
	*/
	DollarFormat string

	/* DollarOrderby.

	   排序
	*/
	DollarOrderby *string

	/* DollarSelect.

	   挑選
	*/
	DollarSelect *string

	/* DollarSkip.

	   跳過前幾筆
	*/
	DollarSkip *string

	/* DollarTop.

	   取前幾筆

	   Default: 30
	*/
	DollarTop *int64

	/* City.

	   欲查詢縣市
	*/
	City string

	/* RouteName.

	   繁體中文路線名稱，如'307'
	*/
	RouteName string

	/* Health.

	   加入參數'?health=true'即可查詢此API服務的健康狀態
	*/
	Health *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the city bus Api route 2035 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CityBusAPIRoute20351Params) WithDefaults() *CityBusAPIRoute20351Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the city bus Api route 2035 1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CityBusAPIRoute20351Params) SetDefaults() {
	var (
		dollarTopDefault = int64(30)
	)

	val := CityBusAPIRoute20351Params{
		DollarTop: &dollarTopDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) WithTimeout(timeout time.Duration) *CityBusAPIRoute20351Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) WithContext(ctx context.Context) *CityBusAPIRoute20351Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) WithHTTPClient(client *http.Client) *CityBusAPIRoute20351Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarFilter adds the dollarFilter to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) WithDollarFilter(dollarFilter *string) *CityBusAPIRoute20351Params {
	o.SetDollarFilter(dollarFilter)
	return o
}

// SetDollarFilter adds the dollarFilter to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) SetDollarFilter(dollarFilter *string) {
	o.DollarFilter = dollarFilter
}

// WithDollarFormat adds the dollarFormat to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) WithDollarFormat(dollarFormat string) *CityBusAPIRoute20351Params {
	o.SetDollarFormat(dollarFormat)
	return o
}

// SetDollarFormat adds the dollarFormat to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) SetDollarFormat(dollarFormat string) {
	o.DollarFormat = dollarFormat
}

// WithDollarOrderby adds the dollarOrderby to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) WithDollarOrderby(dollarOrderby *string) *CityBusAPIRoute20351Params {
	o.SetDollarOrderby(dollarOrderby)
	return o
}

// SetDollarOrderby adds the dollarOrderby to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) SetDollarOrderby(dollarOrderby *string) {
	o.DollarOrderby = dollarOrderby
}

// WithDollarSelect adds the dollarSelect to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) WithDollarSelect(dollarSelect *string) *CityBusAPIRoute20351Params {
	o.SetDollarSelect(dollarSelect)
	return o
}

// SetDollarSelect adds the dollarSelect to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) SetDollarSelect(dollarSelect *string) {
	o.DollarSelect = dollarSelect
}

// WithDollarSkip adds the dollarSkip to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) WithDollarSkip(dollarSkip *string) *CityBusAPIRoute20351Params {
	o.SetDollarSkip(dollarSkip)
	return o
}

// SetDollarSkip adds the dollarSkip to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) SetDollarSkip(dollarSkip *string) {
	o.DollarSkip = dollarSkip
}

// WithDollarTop adds the dollarTop to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) WithDollarTop(dollarTop *int64) *CityBusAPIRoute20351Params {
	o.SetDollarTop(dollarTop)
	return o
}

// SetDollarTop adds the dollarTop to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) SetDollarTop(dollarTop *int64) {
	o.DollarTop = dollarTop
}

// WithCity adds the city to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) WithCity(city string) *CityBusAPIRoute20351Params {
	o.SetCity(city)
	return o
}

// SetCity adds the city to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) SetCity(city string) {
	o.City = city
}

// WithRouteName adds the routeName to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) WithRouteName(routeName string) *CityBusAPIRoute20351Params {
	o.SetRouteName(routeName)
	return o
}

// SetRouteName adds the routeName to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) SetRouteName(routeName string) {
	o.RouteName = routeName
}

// WithHealth adds the health to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) WithHealth(health *string) *CityBusAPIRoute20351Params {
	o.SetHealth(health)
	return o
}

// SetHealth adds the health to the city bus Api route 2035 1 params
func (o *CityBusAPIRoute20351Params) SetHealth(health *string) {
	o.Health = health
}

// WriteToRequest writes these params to a swagger request
func (o *CityBusAPIRoute20351Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DollarFilter != nil {

		// query param $filter
		var qrDollarFilter string

		if o.DollarFilter != nil {
			qrDollarFilter = *o.DollarFilter
		}
		qDollarFilter := qrDollarFilter
		if qDollarFilter != "" {

			if err := r.SetQueryParam("$filter", qDollarFilter); err != nil {
				return err
			}
		}
	}

	// query param $format
	qrDollarFormat := o.DollarFormat
	qDollarFormat := qrDollarFormat
	if qDollarFormat != "" {

		if err := r.SetQueryParam("$format", qDollarFormat); err != nil {
			return err
		}
	}

	if o.DollarOrderby != nil {

		// query param $orderby
		var qrDollarOrderby string

		if o.DollarOrderby != nil {
			qrDollarOrderby = *o.DollarOrderby
		}
		qDollarOrderby := qrDollarOrderby
		if qDollarOrderby != "" {

			if err := r.SetQueryParam("$orderby", qDollarOrderby); err != nil {
				return err
			}
		}
	}

	if o.DollarSelect != nil {

		// query param $select
		var qrDollarSelect string

		if o.DollarSelect != nil {
			qrDollarSelect = *o.DollarSelect
		}
		qDollarSelect := qrDollarSelect
		if qDollarSelect != "" {

			if err := r.SetQueryParam("$select", qDollarSelect); err != nil {
				return err
			}
		}
	}

	if o.DollarSkip != nil {

		// query param $skip
		var qrDollarSkip string

		if o.DollarSkip != nil {
			qrDollarSkip = *o.DollarSkip
		}
		qDollarSkip := qrDollarSkip
		if qDollarSkip != "" {

			if err := r.SetQueryParam("$skip", qDollarSkip); err != nil {
				return err
			}
		}
	}

	if o.DollarTop != nil {

		// query param $top
		var qrDollarTop int64

		if o.DollarTop != nil {
			qrDollarTop = *o.DollarTop
		}
		qDollarTop := swag.FormatInt64(qrDollarTop)
		if qDollarTop != "" {

			if err := r.SetQueryParam("$top", qDollarTop); err != nil {
				return err
			}
		}
	}

	// path param City
	if err := r.SetPathParam("City", o.City); err != nil {
		return err
	}

	// path param RouteName
	if err := r.SetPathParam("RouteName", o.RouteName); err != nil {
		return err
	}

	if o.Health != nil {

		// query param health
		var qrHealth string

		if o.Health != nil {
			qrHealth = *o.Health
		}
		qHealth := qrHealth
		if qHealth != "" {

			if err := r.SetQueryParam("health", qHealth); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
