// Code generated by go-swagger; DO NOT EDIT.

package t_r_a

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/go-ptx/rail/v3/models"
)

// GeneralTrainTimetableAPIControllerGetReader is a Reader for the GeneralTrainTimetableAPIControllerGet structure.
type GeneralTrainTimetableAPIControllerGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GeneralTrainTimetableAPIControllerGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGeneralTrainTimetableAPIControllerGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 299:
		result := NewGeneralTrainTimetableAPIControllerGetStatus299()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewGeneralTrainTimetableAPIControllerGetNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGeneralTrainTimetableAPIControllerGetOK creates a GeneralTrainTimetableAPIControllerGetOK with default headers values
func NewGeneralTrainTimetableAPIControllerGetOK() *GeneralTrainTimetableAPIControllerGetOK {
	return &GeneralTrainTimetableAPIControllerGetOK{}
}

/* GeneralTrainTimetableAPIControllerGetOK describes a response with status code 200, with default header values.

Success
*/
type GeneralTrainTimetableAPIControllerGetOK struct {
	Payload *models.PTXAPIRailModelTRAGeneralTrainWrapperPTXServiceDTORailSpecificationV3TRAGeneralTrainTimetable
}

func (o *GeneralTrainTimetableAPIControllerGetOK) Error() string {
	return fmt.Sprintf("[GET /v3/Rail/TRA/GeneralTrainTimetable][%d] generalTrainTimetableApiControllerGetOK  %+v", 200, o.Payload)
}
func (o *GeneralTrainTimetableAPIControllerGetOK) GetPayload() *models.PTXAPIRailModelTRAGeneralTrainWrapperPTXServiceDTORailSpecificationV3TRAGeneralTrainTimetable {
	return o.Payload
}

func (o *GeneralTrainTimetableAPIControllerGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PTXAPIRailModelTRAGeneralTrainWrapperPTXServiceDTORailSpecificationV3TRAGeneralTrainTimetable)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGeneralTrainTimetableAPIControllerGetStatus299 creates a GeneralTrainTimetableAPIControllerGetStatus299 with default headers values
func NewGeneralTrainTimetableAPIControllerGetStatus299() *GeneralTrainTimetableAPIControllerGetStatus299 {
	return &GeneralTrainTimetableAPIControllerGetStatus299{}
}

/* GeneralTrainTimetableAPIControllerGetStatus299 describes a response with status code 299, with default header values.

加入參數'?health=true'即可查詢此API服務的健康狀態
*/
type GeneralTrainTimetableAPIControllerGetStatus299 struct {
	Payload *models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth
}

func (o *GeneralTrainTimetableAPIControllerGetStatus299) Error() string {
	return fmt.Sprintf("[GET /v3/Rail/TRA/GeneralTrainTimetable][%d] generalTrainTimetableApiControllerGetStatus299  %+v", 299, o.Payload)
}
func (o *GeneralTrainTimetableAPIControllerGetStatus299) GetPayload() *models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth {
	return o.Payload
}

func (o *GeneralTrainTimetableAPIControllerGetStatus299) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGeneralTrainTimetableAPIControllerGetNotModified creates a GeneralTrainTimetableAPIControllerGetNotModified with default headers values
func NewGeneralTrainTimetableAPIControllerGetNotModified() *GeneralTrainTimetableAPIControllerGetNotModified {
	return &GeneralTrainTimetableAPIControllerGetNotModified{}
}

/* GeneralTrainTimetableAPIControllerGetNotModified describes a response with status code 304, with default header values.

服務端會在Response加上Last-Modified header，表示最近的更新時間。客戶端能利用此時間，於Request加上If-Modified-Since header，若沒有更新，服務端會回應304 StatusCode且空值Content
*/
type GeneralTrainTimetableAPIControllerGetNotModified struct {
}

func (o *GeneralTrainTimetableAPIControllerGetNotModified) Error() string {
	return fmt.Sprintf("[GET /v3/Rail/TRA/GeneralTrainTimetable][%d] generalTrainTimetableApiControllerGetNotModified ", 304)
}

func (o *GeneralTrainTimetableAPIControllerGetNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
