// Code generated by go-swagger; DO NOT EDIT.

package t_r_a

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/go-ptx/rail/v3/models"
)

// ShapeAPIControllerGetReader is a Reader for the ShapeAPIControllerGet structure.
type ShapeAPIControllerGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ShapeAPIControllerGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewShapeAPIControllerGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 299:
		result := NewShapeAPIControllerGetStatus299()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewShapeAPIControllerGetNotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewShapeAPIControllerGetOK creates a ShapeAPIControllerGetOK with default headers values
func NewShapeAPIControllerGetOK() *ShapeAPIControllerGetOK {
	return &ShapeAPIControllerGetOK{}
}

/* ShapeAPIControllerGetOK describes a response with status code 200, with default header values.

Success
*/
type ShapeAPIControllerGetOK struct {
	Payload *models.PTXAPIRailModelTRABaseWrapperPTXServiceDTORailSpecificationV3TRAShape
}

func (o *ShapeAPIControllerGetOK) Error() string {
	return fmt.Sprintf("[GET /v3/Rail/TRA/Shape][%d] shapeApiControllerGetOK  %+v", 200, o.Payload)
}
func (o *ShapeAPIControllerGetOK) GetPayload() *models.PTXAPIRailModelTRABaseWrapperPTXServiceDTORailSpecificationV3TRAShape {
	return o.Payload
}

func (o *ShapeAPIControllerGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PTXAPIRailModelTRABaseWrapperPTXServiceDTORailSpecificationV3TRAShape)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShapeAPIControllerGetStatus299 creates a ShapeAPIControllerGetStatus299 with default headers values
func NewShapeAPIControllerGetStatus299() *ShapeAPIControllerGetStatus299 {
	return &ShapeAPIControllerGetStatus299{}
}

/* ShapeAPIControllerGetStatus299 describes a response with status code 299, with default header values.

加入參數'?health=true'即可查詢此API服務的健康狀態
*/
type ShapeAPIControllerGetStatus299 struct {
	Payload *models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth
}

func (o *ShapeAPIControllerGetStatus299) Error() string {
	return fmt.Sprintf("[GET /v3/Rail/TRA/Shape][%d] shapeApiControllerGetStatus299  %+v", 299, o.Payload)
}
func (o *ShapeAPIControllerGetStatus299) GetPayload() *models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth {
	return o.Payload
}

func (o *ShapeAPIControllerGetStatus299) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewShapeAPIControllerGetNotModified creates a ShapeAPIControllerGetNotModified with default headers values
func NewShapeAPIControllerGetNotModified() *ShapeAPIControllerGetNotModified {
	return &ShapeAPIControllerGetNotModified{}
}

/* ShapeAPIControllerGetNotModified describes a response with status code 304, with default header values.

服務端會在Response加上Last-Modified header，表示最近的更新時間。客戶端能利用此時間，於Request加上If-Modified-Since header，若沒有更新，服務端會回應304 StatusCode且空值Content
*/
type ShapeAPIControllerGetNotModified struct {
}

func (o *ShapeAPIControllerGetNotModified) Error() string {
	return fmt.Sprintf("[GET /v3/Rail/TRA/Shape][%d] shapeApiControllerGetNotModified ", 304)
}

func (o *ShapeAPIControllerGetNotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
