// Code generated by go-swagger; DO NOT EDIT.

package t_r_a

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/go-ptx/rail/v3/models"
)

// StationLiveBoardAPIControllerGet1Reader is a Reader for the StationLiveBoardAPIControllerGet1 structure.
type StationLiveBoardAPIControllerGet1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StationLiveBoardAPIControllerGet1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewStationLiveBoardAPIControllerGet1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewStationLiveBoardAPIControllerGet1NotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewStationLiveBoardAPIControllerGet1OK creates a StationLiveBoardAPIControllerGet1OK with default headers values
func NewStationLiveBoardAPIControllerGet1OK() *StationLiveBoardAPIControllerGet1OK {
	return &StationLiveBoardAPIControllerGet1OK{}
}

/* StationLiveBoardAPIControllerGet1OK describes a response with status code 200, with default header values.

Success
*/
type StationLiveBoardAPIControllerGet1OK struct {
	Payload *models.PTXAPIRailModelTRARealTimeWrapperPTXServiceDTORailSpecificationV3TRATRAStationLiveBoardListStationLiveBoard
}

func (o *StationLiveBoardAPIControllerGet1OK) Error() string {
	return fmt.Sprintf("[GET /v3/Rail/TRA/StationLiveBoard/Station/{StationID}][%d] stationLiveBoardApiControllerGet1OK  %+v", 200, o.Payload)
}
func (o *StationLiveBoardAPIControllerGet1OK) GetPayload() *models.PTXAPIRailModelTRARealTimeWrapperPTXServiceDTORailSpecificationV3TRATRAStationLiveBoardListStationLiveBoard {
	return o.Payload
}

func (o *StationLiveBoardAPIControllerGet1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PTXAPIRailModelTRARealTimeWrapperPTXServiceDTORailSpecificationV3TRATRAStationLiveBoardListStationLiveBoard)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewStationLiveBoardAPIControllerGet1NotModified creates a StationLiveBoardAPIControllerGet1NotModified with default headers values
func NewStationLiveBoardAPIControllerGet1NotModified() *StationLiveBoardAPIControllerGet1NotModified {
	return &StationLiveBoardAPIControllerGet1NotModified{}
}

/* StationLiveBoardAPIControllerGet1NotModified describes a response with status code 304, with default header values.

服務端會在Response加上Last-Modified header，表示最近的更新時間。客戶端能利用此時間，於Request加上If-Modified-Since header，若沒有更新，服務端會回應304 StatusCode且空值Content
*/
type StationLiveBoardAPIControllerGet1NotModified struct {
}

func (o *StationLiveBoardAPIControllerGet1NotModified) Error() string {
	return fmt.Sprintf("[GET /v3/Rail/TRA/StationLiveBoard/Station/{StationID}][%d] stationLiveBoardApiControllerGet1NotModified ", 304)
}

func (o *StationLiveBoardAPIControllerGet1NotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
