// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PTXServiceDTOTourismSpecificationV2BusTaiwanTripS2STravelTimeTravelTime TravelTime
//
// swagger:model PTX.Service.DTO.Tourism.Specification.V2.BusTaiwanTripS2STravelTime+TravelTime
type PTXServiceDTOTourismSpecificationV2BusTaiwanTripS2STravelTimeTravelTime struct {

	// Single
	//
	// 站間距離
	// Required: true
	Distance *float32 `json:"Distance"`

	// String
	//
	// 起站站牌代碼
	// Required: true
	FromStopID *string `json:"FromStopID" xml:"FromStopID"`

	// Int32
	//
	// 站間預估行駛時間
	// Required: true
	RunTime *int32 `json:"RunTime"`

	// Int32
	//
	// 站間序號
	// Required: true
	Sequence *int32 `json:"Sequence"`

	// Int32
	//
	// 起站停靠時間
	// Required: true
	StopTime *int32 `json:"StopTime"`

	// String
	//
	// 迄站站牌代碼
	// Required: true
	ToStopID *string `json:"ToStopID" xml:"ToStopID"`
}

// Validate validates this p t x service d t o tourism specification v2 bus taiwan trip s2 s travel time travel time
func (m *PTXServiceDTOTourismSpecificationV2BusTaiwanTripS2STravelTimeTravelTime) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDistance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFromStopID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRunTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSequence(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStopTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToStopID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PTXServiceDTOTourismSpecificationV2BusTaiwanTripS2STravelTimeTravelTime) validateDistance(formats strfmt.Registry) error {

	if err := validate.Required("Distance", "body", m.Distance); err != nil {
		return err
	}

	return nil
}

func (m *PTXServiceDTOTourismSpecificationV2BusTaiwanTripS2STravelTimeTravelTime) validateFromStopID(formats strfmt.Registry) error {

	if err := validate.Required("FromStopID", "body", m.FromStopID); err != nil {
		return err
	}

	return nil
}

func (m *PTXServiceDTOTourismSpecificationV2BusTaiwanTripS2STravelTimeTravelTime) validateRunTime(formats strfmt.Registry) error {

	if err := validate.Required("RunTime", "body", m.RunTime); err != nil {
		return err
	}

	return nil
}

func (m *PTXServiceDTOTourismSpecificationV2BusTaiwanTripS2STravelTimeTravelTime) validateSequence(formats strfmt.Registry) error {

	if err := validate.Required("Sequence", "body", m.Sequence); err != nil {
		return err
	}

	return nil
}

func (m *PTXServiceDTOTourismSpecificationV2BusTaiwanTripS2STravelTimeTravelTime) validateStopTime(formats strfmt.Registry) error {

	if err := validate.Required("StopTime", "body", m.StopTime); err != nil {
		return err
	}

	return nil
}

func (m *PTXServiceDTOTourismSpecificationV2BusTaiwanTripS2STravelTimeTravelTime) validateToStopID(formats strfmt.Registry) error {

	if err := validate.Required("ToStopID", "body", m.ToStopID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this p t x service d t o tourism specification v2 bus taiwan trip s2 s travel time travel time based on context it is used
func (m *PTXServiceDTOTourismSpecificationV2BusTaiwanTripS2STravelTimeTravelTime) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PTXServiceDTOTourismSpecificationV2BusTaiwanTripS2STravelTimeTravelTime) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PTXServiceDTOTourismSpecificationV2BusTaiwanTripS2STravelTimeTravelTime) UnmarshalBinary(b []byte) error {
	var res PTXServiceDTOTourismSpecificationV2BusTaiwanTripS2STravelTimeTravelTime
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
