// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ServiceDTOVersion3BusScheduleServiceDay ServiceDay
// swagger:model Service.DTO.Version3.Bus.Schedule.ServiceDay
type ServiceDTOVersion3BusScheduleServiceDay struct {

	// 國定假日後一日營運與否
	DayAfterHoliday bool `json:"DayAfterHoliday,omitempty"`

	// 國定假日前一日營運與否
	DayBeforeHoliday bool `json:"DayBeforeHoliday,omitempty"`

	// 星期五營運與否
	Friday bool `json:"Friday,omitempty"`

	// 星期一營運與否
	Monday bool `json:"Monday,omitempty"`

	// 國定假日營運與否
	NationalHolidays bool `json:"NationalHolidays,omitempty"`

	// 星期六營運與否
	Saturday bool `json:"Saturday,omitempty"`

	// 服務日標籤
	ServiceTag string `json:"ServiceTag,omitempty"`

	// 星期日營運與否
	Sunday bool `json:"Sunday,omitempty"`

	// 星期四營運與否
	Thursday bool `json:"Thursday,omitempty"`

	// 星期二營運與否
	Tuesday bool `json:"Tuesday,omitempty"`

	// 颱風停止上班上課期間營運與否
	TyphoonDay bool `json:"TyphoonDay,omitempty"`

	// 星期三營運與否
	Wednesday bool `json:"Wednesday,omitempty"`
}

// Validate validates this service d t o version3 bus schedule service day
func (m *ServiceDTOVersion3BusScheduleServiceDay) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceDTOVersion3BusScheduleServiceDay) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceDTOVersion3BusScheduleServiceDay) UnmarshalBinary(b []byte) error {
	var res ServiceDTOVersion3BusScheduleServiceDay
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
