// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ServiceDTOVersion3BusRouteNetworkSegment Segment
//
// swagger:model Service.DTO.Version3.Bus.RouteNetwork.Segment
type ServiceDTOVersion3BusRouteNetworkSegment struct {

	// 站間線段距離
	// Required: true
	Distance *float32 `json:"Distance"`

	// 表BusStop唯一碼(起點站牌)
	// Required: true
	FromStopID *string `json:"FromStopID"`

	// 站間線段序號
	// Required: true
	Sequence *float32 `json:"Sequence"`

	// 表BusStop唯一碼(迄點站牌)
	// Required: true
	ToStopID *string `json:"ToStopID"`
}

// Validate validates this service d t o version3 bus route network segment
func (m *ServiceDTOVersion3BusRouteNetworkSegment) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDistance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFromStopID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSequence(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToStopID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ServiceDTOVersion3BusRouteNetworkSegment) validateDistance(formats strfmt.Registry) error {

	if err := validate.Required("Distance", "body", m.Distance); err != nil {
		return err
	}

	return nil
}

func (m *ServiceDTOVersion3BusRouteNetworkSegment) validateFromStopID(formats strfmt.Registry) error {

	if err := validate.Required("FromStopID", "body", m.FromStopID); err != nil {
		return err
	}

	return nil
}

func (m *ServiceDTOVersion3BusRouteNetworkSegment) validateSequence(formats strfmt.Registry) error {

	if err := validate.Required("Sequence", "body", m.Sequence); err != nil {
		return err
	}

	return nil
}

func (m *ServiceDTOVersion3BusRouteNetworkSegment) validateToStopID(formats strfmt.Registry) error {

	if err := validate.Required("ToStopID", "body", m.ToStopID); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ServiceDTOVersion3BusRouteNetworkSegment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceDTOVersion3BusRouteNetworkSegment) UnmarshalBinary(b []byte) error {
	var res ServiceDTOVersion3BusRouteNetworkSegment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
