// Code generated by go-swagger; DO NOT EDIT.

package metro

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewMetroAPILineTransferParams creates a new MetroAPILineTransferParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMetroAPILineTransferParams() *MetroAPILineTransferParams {
	return &MetroAPILineTransferParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMetroAPILineTransferParamsWithTimeout creates a new MetroAPILineTransferParams object
// with the ability to set a timeout on a request.
func NewMetroAPILineTransferParamsWithTimeout(timeout time.Duration) *MetroAPILineTransferParams {
	return &MetroAPILineTransferParams{
		timeout: timeout,
	}
}

// NewMetroAPILineTransferParamsWithContext creates a new MetroAPILineTransferParams object
// with the ability to set a context for a request.
func NewMetroAPILineTransferParamsWithContext(ctx context.Context) *MetroAPILineTransferParams {
	return &MetroAPILineTransferParams{
		Context: ctx,
	}
}

// NewMetroAPILineTransferParamsWithHTTPClient creates a new MetroAPILineTransferParams object
// with the ability to set a custom HTTPClient for a request.
func NewMetroAPILineTransferParamsWithHTTPClient(client *http.Client) *MetroAPILineTransferParams {
	return &MetroAPILineTransferParams{
		HTTPClient: client,
	}
}

/* MetroAPILineTransferParams contains all the parameters to send to the API endpoint
   for the metro Api line transfer operation.

   Typically these are written to a http.Request.
*/
type MetroAPILineTransferParams struct {

	/* DollarFilter.

	   過濾
	*/
	DollarFilter *string

	/* DollarFormat.

	   指定來源格式
	*/
	DollarFormat string

	/* DollarOrderby.

	   排序
	*/
	DollarOrderby *string

	/* DollarSelect.

	   挑選
	*/
	DollarSelect *string

	/* DollarSkip.

	   跳過前幾筆
	*/
	DollarSkip *string

	/* DollarTop.

	   取前幾筆

	   Default: 30
	*/
	DollarTop *int64

	/* Operator.

	   欲查詢縣市
	*/
	Operator string

	/* Health.

	   加入參數'?health=true'即可查詢此API服務的健康狀態
	*/
	Health *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the metro Api line transfer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MetroAPILineTransferParams) WithDefaults() *MetroAPILineTransferParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the metro Api line transfer params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MetroAPILineTransferParams) SetDefaults() {
	var (
		dollarTopDefault = int64(30)
	)

	val := MetroAPILineTransferParams{
		DollarTop: &dollarTopDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the metro Api line transfer params
func (o *MetroAPILineTransferParams) WithTimeout(timeout time.Duration) *MetroAPILineTransferParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the metro Api line transfer params
func (o *MetroAPILineTransferParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the metro Api line transfer params
func (o *MetroAPILineTransferParams) WithContext(ctx context.Context) *MetroAPILineTransferParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the metro Api line transfer params
func (o *MetroAPILineTransferParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the metro Api line transfer params
func (o *MetroAPILineTransferParams) WithHTTPClient(client *http.Client) *MetroAPILineTransferParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the metro Api line transfer params
func (o *MetroAPILineTransferParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDollarFilter adds the dollarFilter to the metro Api line transfer params
func (o *MetroAPILineTransferParams) WithDollarFilter(dollarFilter *string) *MetroAPILineTransferParams {
	o.SetDollarFilter(dollarFilter)
	return o
}

// SetDollarFilter adds the dollarFilter to the metro Api line transfer params
func (o *MetroAPILineTransferParams) SetDollarFilter(dollarFilter *string) {
	o.DollarFilter = dollarFilter
}

// WithDollarFormat adds the dollarFormat to the metro Api line transfer params
func (o *MetroAPILineTransferParams) WithDollarFormat(dollarFormat string) *MetroAPILineTransferParams {
	o.SetDollarFormat(dollarFormat)
	return o
}

// SetDollarFormat adds the dollarFormat to the metro Api line transfer params
func (o *MetroAPILineTransferParams) SetDollarFormat(dollarFormat string) {
	o.DollarFormat = dollarFormat
}

// WithDollarOrderby adds the dollarOrderby to the metro Api line transfer params
func (o *MetroAPILineTransferParams) WithDollarOrderby(dollarOrderby *string) *MetroAPILineTransferParams {
	o.SetDollarOrderby(dollarOrderby)
	return o
}

// SetDollarOrderby adds the dollarOrderby to the metro Api line transfer params
func (o *MetroAPILineTransferParams) SetDollarOrderby(dollarOrderby *string) {
	o.DollarOrderby = dollarOrderby
}

// WithDollarSelect adds the dollarSelect to the metro Api line transfer params
func (o *MetroAPILineTransferParams) WithDollarSelect(dollarSelect *string) *MetroAPILineTransferParams {
	o.SetDollarSelect(dollarSelect)
	return o
}

// SetDollarSelect adds the dollarSelect to the metro Api line transfer params
func (o *MetroAPILineTransferParams) SetDollarSelect(dollarSelect *string) {
	o.DollarSelect = dollarSelect
}

// WithDollarSkip adds the dollarSkip to the metro Api line transfer params
func (o *MetroAPILineTransferParams) WithDollarSkip(dollarSkip *string) *MetroAPILineTransferParams {
	o.SetDollarSkip(dollarSkip)
	return o
}

// SetDollarSkip adds the dollarSkip to the metro Api line transfer params
func (o *MetroAPILineTransferParams) SetDollarSkip(dollarSkip *string) {
	o.DollarSkip = dollarSkip
}

// WithDollarTop adds the dollarTop to the metro Api line transfer params
func (o *MetroAPILineTransferParams) WithDollarTop(dollarTop *int64) *MetroAPILineTransferParams {
	o.SetDollarTop(dollarTop)
	return o
}

// SetDollarTop adds the dollarTop to the metro Api line transfer params
func (o *MetroAPILineTransferParams) SetDollarTop(dollarTop *int64) {
	o.DollarTop = dollarTop
}

// WithOperator adds the operator to the metro Api line transfer params
func (o *MetroAPILineTransferParams) WithOperator(operator string) *MetroAPILineTransferParams {
	o.SetOperator(operator)
	return o
}

// SetOperator adds the operator to the metro Api line transfer params
func (o *MetroAPILineTransferParams) SetOperator(operator string) {
	o.Operator = operator
}

// WithHealth adds the health to the metro Api line transfer params
func (o *MetroAPILineTransferParams) WithHealth(health *string) *MetroAPILineTransferParams {
	o.SetHealth(health)
	return o
}

// SetHealth adds the health to the metro Api line transfer params
func (o *MetroAPILineTransferParams) SetHealth(health *string) {
	o.Health = health
}

// WriteToRequest writes these params to a swagger request
func (o *MetroAPILineTransferParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DollarFilter != nil {

		// query param $filter
		var qrDollarFilter string

		if o.DollarFilter != nil {
			qrDollarFilter = *o.DollarFilter
		}
		qDollarFilter := qrDollarFilter
		if qDollarFilter != "" {

			if err := r.SetQueryParam("$filter", qDollarFilter); err != nil {
				return err
			}
		}
	}

	// query param $format
	qrDollarFormat := o.DollarFormat
	qDollarFormat := qrDollarFormat
	if qDollarFormat != "" {

		if err := r.SetQueryParam("$format", qDollarFormat); err != nil {
			return err
		}
	}

	if o.DollarOrderby != nil {

		// query param $orderby
		var qrDollarOrderby string

		if o.DollarOrderby != nil {
			qrDollarOrderby = *o.DollarOrderby
		}
		qDollarOrderby := qrDollarOrderby
		if qDollarOrderby != "" {

			if err := r.SetQueryParam("$orderby", qDollarOrderby); err != nil {
				return err
			}
		}
	}

	if o.DollarSelect != nil {

		// query param $select
		var qrDollarSelect string

		if o.DollarSelect != nil {
			qrDollarSelect = *o.DollarSelect
		}
		qDollarSelect := qrDollarSelect
		if qDollarSelect != "" {

			if err := r.SetQueryParam("$select", qDollarSelect); err != nil {
				return err
			}
		}
	}

	if o.DollarSkip != nil {

		// query param $skip
		var qrDollarSkip string

		if o.DollarSkip != nil {
			qrDollarSkip = *o.DollarSkip
		}
		qDollarSkip := qrDollarSkip
		if qDollarSkip != "" {

			if err := r.SetQueryParam("$skip", qDollarSkip); err != nil {
				return err
			}
		}
	}

	if o.DollarTop != nil {

		// query param $top
		var qrDollarTop int64

		if o.DollarTop != nil {
			qrDollarTop = *o.DollarTop
		}
		qDollarTop := swag.FormatInt64(qrDollarTop)
		if qDollarTop != "" {

			if err := r.SetQueryParam("$top", qDollarTop); err != nil {
				return err
			}
		}
	}

	// path param Operator
	if err := r.SetPathParam("Operator", o.Operator); err != nil {
		return err
	}

	if o.Health != nil {

		// query param health
		var qrHealth string

		if o.Health != nil {
			qrHealth = *o.Health
		}
		qHealth := qrHealth
		if qHealth != "" {

			if err := r.SetQueryParam("health", qHealth); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
