// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PTXServiceDTOBusSpecificationV2SectionFareStop Stop
//
// swagger:model PTX.Service.DTO.Bus.Specification.V2.SectionFare+Stop
type PTXServiceDTOBusSpecificationV2SectionFareStop struct {

	// String
	//
	// 緩衝區站牌代碼
	// Required: true
	StopID *string `json:"StopID"`

	// String
	//
	// 站牌名稱
	// Required: true
	StopName *string `json:"StopName"`
}

// Validate validates this p t x service d t o bus specification v2 section fare stop
func (m *PTXServiceDTOBusSpecificationV2SectionFareStop) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStopID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStopName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PTXServiceDTOBusSpecificationV2SectionFareStop) validateStopID(formats strfmt.Registry) error {

	if err := validate.Required("StopID", "body", m.StopID); err != nil {
		return err
	}

	return nil
}

func (m *PTXServiceDTOBusSpecificationV2SectionFareStop) validateStopName(formats strfmt.Registry) error {

	if err := validate.Required("StopName", "body", m.StopName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PTXServiceDTOBusSpecificationV2SectionFareStop) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PTXServiceDTOBusSpecificationV2SectionFareStop) UnmarshalBinary(b []byte) error {
	var res PTXServiceDTOBusSpecificationV2SectionFareStop
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
