// Code generated by go-swagger; DO NOT EDIT.

package city_bus

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/minchao/go-ptx/bus/v3/models"
)

// CityBusAPIShape2Reader is a Reader for the CityBusAPIShape2 structure.
type CityBusAPIShape2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CityBusAPIShape2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewCityBusAPIShape2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCityBusAPIShape2OK creates a CityBusAPIShape2OK with default headers values
func NewCityBusAPIShape2OK() *CityBusAPIShape2OK {
	return &CityBusAPIShape2OK{}
}

/*CityBusAPIShape2OK handles this case with default header values.

OK
*/
type CityBusAPIShape2OK struct {
	Payload *models.MOTCAPIBusDALBusServiceDTOVersion3BusShape
}

func (o *CityBusAPIShape2OK) Error() string {
	return fmt.Sprintf("[GET /v3/Bus/Shape/City/{City}][%d] cityBusApiShape2OK  %+v", 200, o.Payload)
}

func (o *CityBusAPIShape2OK) GetPayload() *models.MOTCAPIBusDALBusServiceDTOVersion3BusShape {
	return o.Payload
}

func (o *CityBusAPIShape2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.MOTCAPIBusDALBusServiceDTOVersion3BusShape)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
