// Code generated by go-swagger; DO NOT EDIT.

package tourism

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/go-ptx/tourism/v2/models"
)

// TourismAPIScenicSpot0Reader is a Reader for the TourismAPIScenicSpot0 structure.
type TourismAPIScenicSpot0Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TourismAPIScenicSpot0Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTourismAPIScenicSpot0OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTourismAPIScenicSpot0OK creates a TourismAPIScenicSpot0OK with default headers values
func NewTourismAPIScenicSpot0OK() *TourismAPIScenicSpot0OK {
	return &TourismAPIScenicSpot0OK{}
}

/*TourismAPIScenicSpot0OK handles this case with default header values.

OK
*/
type TourismAPIScenicSpot0OK struct {
	Payload []*models.ServiceDTOVersion2ApplicationScenicSpotTourismInfo
}

func (o *TourismAPIScenicSpot0OK) Error() string {
	return fmt.Sprintf("[GET /v2/Tourism/ScenicSpot/{City}][%d] tourismApiScenicSpot0OK  %+v", 200, o.Payload)
}

func (o *TourismAPIScenicSpot0OK) GetPayload() []*models.ServiceDTOVersion2ApplicationScenicSpotTourismInfo {
	return o.Payload
}

func (o *TourismAPIScenicSpot0OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
