// Code generated by go-swagger; DO NOT EDIT.

package tourism

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/minchao/go-ptx/tourism/v2/models"
)

// TourismAPIActivity2246Reader is a Reader for the TourismAPIActivity2246 structure.
type TourismAPIActivity2246Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TourismAPIActivity2246Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTourismAPIActivity2246OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 299:
		result := NewTourismAPIActivity2246Status299()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 304:
		result := NewTourismAPIActivity2246NotModified()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewTourismAPIActivity2246OK creates a TourismAPIActivity2246OK with default headers values
func NewTourismAPIActivity2246OK() *TourismAPIActivity2246OK {
	return &TourismAPIActivity2246OK{}
}

/* TourismAPIActivity2246OK describes a response with status code 200, with default header values.

Success
*/
type TourismAPIActivity2246OK struct {
	Payload []*models.PTXServiceDTOTourismSpecificationV2ActivityTourismInfo
}

func (o *TourismAPIActivity2246OK) Error() string {
	return fmt.Sprintf("[GET /v2/Tourism/Activity][%d] tourismApiActivity2246OK  %+v", 200, o.Payload)
}
func (o *TourismAPIActivity2246OK) GetPayload() []*models.PTXServiceDTOTourismSpecificationV2ActivityTourismInfo {
	return o.Payload
}

func (o *TourismAPIActivity2246OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTourismAPIActivity2246Status299 creates a TourismAPIActivity2246Status299 with default headers values
func NewTourismAPIActivity2246Status299() *TourismAPIActivity2246Status299 {
	return &TourismAPIActivity2246Status299{}
}

/* TourismAPIActivity2246Status299 describes a response with status code 299, with default header values.

加入參數'?health=true'即可查詢此API服務的健康狀態
*/
type TourismAPIActivity2246Status299 struct {
	Payload *models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth
}

func (o *TourismAPIActivity2246Status299) Error() string {
	return fmt.Sprintf("[GET /v2/Tourism/Activity][%d] tourismApiActivity2246Status299  %+v", 299, o.Payload)
}
func (o *TourismAPIActivity2246Status299) GetPayload() *models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth {
	return o.Payload
}

func (o *TourismAPIActivity2246Status299) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PTXServiceDTOSharedSpecificationV3BaseDisplayHealth)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTourismAPIActivity2246NotModified creates a TourismAPIActivity2246NotModified with default headers values
func NewTourismAPIActivity2246NotModified() *TourismAPIActivity2246NotModified {
	return &TourismAPIActivity2246NotModified{}
}

/* TourismAPIActivity2246NotModified describes a response with status code 304, with default header values.

服務端會在Response加上Last-Modified header，表示最近的更新時間。客戶端能利用此時間，於Request加上If-Modified-Since header，若沒有更新，服務端會回應304 StatusCode且空值Content
*/
type TourismAPIActivity2246NotModified struct {
}

func (o *TourismAPIActivity2246NotModified) Error() string {
	return fmt.Sprintf("[GET /v2/Tourism/Activity][%d] tourismApiActivity2246NotModified ", 304)
}

func (o *TourismAPIActivity2246NotModified) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
